[version]
15574

[xenonbl]
SB_10375.bin,814c81b8
SC_17489_xenon.bin,787c2968
SD_17489.bin,ba7a0f91
SE_15574.bin,96f15489
none,00000000
none,00000000

[zephyrbl]
SB_10375.bin,814c81b8
SC_17489.bin,c665b4ec
SD_17489.bin,ba7a0f91
SE_15574.bin,96f15489
none,00000000
none,00000000

[falconbl]
SB_10375.bin,814c81b8
SC_17489.bin,c665b4ec
SD_17489.bin,ba7a0f91
SE_15574.bin,96f15489
none,00000000
none,00000000

[jasperbl]
SB_10375.bin,814c81b8
SC_17489.bin,c665b4ec
SD_17489.bin,ba7a0f91
SE_15574.bin,96f15489
none,00000000
none,00000000

[security]
crl.bin,
dae.bin,
extended.bin,
fcrt.bin,
secdata.bin,

;On a Devkit NAND, xeBuld expects the patch slot to be at
;0xE4000. However, regular devGL patches expect it to be
;at 0xE0000. To be able to use standard DevGL patches on
;a 64mb devGL image (XeLL will not work due to the flashfs
;offset difference), the following lines can be added to
;the rawpatch section below and vfuses_khv.bin can be
;changed to 0xE0000.
; 
;devgl64_patch_0x64.bin,0x64
;devgl64_patch_0x70.bin,0x70
;
;On a standard devkit NAND, 0x64 is set to 0x000D4000, while
;0x70 is set to 0x00010000, which means that the system update
;slot is 0x4000 later in NAND compared to a standard DevGL image
;and both the SD and SE patches need to be updated to be able
;to handle images without the patchslot address change
;
[rawpatch]
vfuses_khv.bin,0xE0000
xell_reason.bin,0x4E

[flashfs]
..\data\xell-gggggg.bin,;
Filesystems\15574-dev\bootanim.xex,
Filesystems\15574-dev\connectx.xex,
Filesystems\15574-dev\createprofile.xex,
Filesystems\15574-dev\dash.xex,
Filesystems\15574-dev\dashboard.xbx,
Filesystems\15574-dev\deviceselector.xex,
Filesystems\15574-dev\gamerprofile.xex,
Filesystems\15574-dev\hud.xex,
Filesystems\15574-dev\huduiskin.xex,
Filesystems\15574-dev\mfgbootlauncher.xex,
Filesystems\15574-dev\minimediaplayer.xex,
Filesystems\15574-dev\nomni.xex,
Filesystems\15574-dev\nomnifwk.xex,
Filesystems\15574-dev\nomnifwm.xex,
Filesystems\15574-dev\processdump.xex,
Filesystems\15574-dev\recovery.ttf,
Filesystems\15574-dev\rrbkgnd.bmp,
Filesystems\15574-dev\SegoeXbox-Light.xtt,
Filesystems\15574-dev\signin.xex,
Filesystems\15574-dev\testxex.xex,
Filesystems\15574-dev\updater.xex,
Filesystems\15574-dev\vk.xex,
Filesystems\15574-dev\xam.xex,
Filesystems\15574-dev\xapid.xex,
Filesystems\15574-dev\xbdm.xex,
Filesystems\15574-dev\xbupdate.xex,
Filesystems\15574-dev\xenonclatin.xtt,
Filesystems\15574-dev\xenonjklatin.xtt,
Filesystems\15574-dev\xenonsclatin.xtt,
Filesystems\15574-dev\ximecore.xex,
Filesystems\15574-dev\ximedic.xex,
Filesystems\15574-dev\ximedic_chs.xex,
Filesystems\15574-dev\xlaunch.fdf,
Filesystems\15574-dev\xlaunch.strings,
Filesystems\15574-dev\xshell.xex,
Filesystems\15574-dev\xstudio.xex,


