[version]
17700

;
; Note: this ini file is used for building a 64mb DevGL
; NAND and requires J-Runner 3.3.0 R5 or later
;

[xenonbl]
SB_10375.bin,814c81b8
SC_17489_xenon.bin,787c2968
SD_17489.bin,ba7a0f91
SE_17700.bin,328b055f
none,00000000
none,00000000

[zephyrbl]
SB_10375.bin,814c81b8
SC_17489.bin,c665b4ec
SD_17489.bin,ba7a0f91
SE_17700.bin,328b055f
none,00000000
none,00000000

[falconbl]
SB_10375.bin,814c81b8
SC_17489.bin,c665b4ec
SD_17489.bin,ba7a0f91
SE_17700.bin,328b055f
none,00000000
none,00000000

[jasperbl]
SB_10375.bin,814c81b8
SC_17489.bin,c665b4ec
SD_17489.bin,ba7a0f91
SE_17700.bin,328b055f
none,00000000
none,00000000

[security]
crl.bin,
dae.bin,
extended.bin,
fcrt.bin,
secdata.bin,

;On a Devkit NAND, xeBuld expects the patch slot to be at
;0xE4000. However, regular devGL patches expect it to be
;at 0xE0000. To be able to use standard DevGL patches on
;a 64mb devGL image (XeLL will not work due to the flashfs
;offset difference), the following lines can be added to
;the rawpatch section below and vfuses_khv.bin can be
;changed to 0xE0000.
; 
;devgl64_patch_0x64.bin,0x64
;devgl64_patch_0x70.bin,0x70
;
;On a standard 17700 NAND, 0x64 is set to 0x000C0000, while
;0x70 is set to 0x00010000, which means that the system update
;slot is 0x4000 later in NAND compared to a standard DevGL image
;and both the SD and SE patches need to be updated to be able
;to handle images without the patchslot address change
;
[rawpatch]
vfuses_khv.bin,0xD0000
xell_reason.bin,0x4E

[flashfs]
..\data\xell-gggggg.bin,;
Filesystems\17700-dev\bootanim.xex,
Filesystems\17700-dev\connectx.xex,
Filesystems\17700-dev\createprofile.xex,
Filesystems\17700-dev\dash.xex,
Filesystems\17700-dev\dashboard.xbx,
Filesystems\17700-dev\deviceselector.xex,
Filesystems\17700-dev\gamerprofile.xex,
Filesystems\17700-dev\hud.xex,
Filesystems\17700-dev\huduiskin.xex,
Filesystems\17700-dev\mfgbootlauncher.xex,
Filesystems\17700-dev\minimediaplayer.xex,
Filesystems\17700-dev\nomni.xex,
Filesystems\17700-dev\nomnifwk.xex,
Filesystems\17700-dev\nomnifwm.xex,
Filesystems\17700-dev\processdump.xex,
Filesystems\17700-dev\recovery.ttf,
Filesystems\17700-dev\rrbkgnd.bmp,
Filesystems\17700-dev\SegoeXbox-Light.xtt,
Filesystems\17700-dev\signin.xex,
Filesystems\17700-dev\updater.xex,
Filesystems\17700-dev\vk.xex,
Filesystems\17700-dev\xam.xex,
Filesystems\17700-dev\xbdm.xex,
Filesystems\17700-dev\xbupdate.xex,
Filesystems\17700-dev\xenonclatin.xtt,
Filesystems\17700-dev\xenonjklatin.xtt,
Filesystems\17700-dev\xenonsclatin.xtt,
Filesystems\17700-dev\ximecore.xex,
Filesystems\17700-dev\ximedic.xex,
Filesystems\17700-dev\xlaunch.fdf,
Filesystems\17700-dev\xlaunch.strings,
Filesystems\17700-dev\xshell.xex,
Filesystems\17700-dev\xstudio.xex,


